language: node_js
node_js:
- '4'
script:
- set -e
- npm run test
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/get-source.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: ibZxun5JP1L9mS22BbDUXMG3F5APKWySGam6MUFZPNP0IULhpiHQ/XaJJhdH6CpAopplgL/ECiGq98sOZf6GMRr99fu8P6i8o6vbzQe+44qo7GoZLwn8538mmj4RBzw3Br8moL7vJi1wbEa0PFOSGzLDpFV6ZwwNEwCIeZvV9+1Toar2HLgGCx8c+lLb0nSzoTIQLnojvt5VYgEhKd/jOfQvLyyfIn2b+REUDgR02Rv5teEOXhXKhuqSuKc5YpFWe0kMeGKnQDWDAeGhNPwHZfWkPn6QpoD2WBT6SCK/Dkf+oXIuzgw9aBlNA/U5qkASqNGgpJ6PfJpdKOaZUGm3SCluHDW92MXuyMZjlzqg+pGhi/teAO0nLNPVcrc2uy0bu9rFVrcmYdWM3C+GpmFBiGKZyJ3TOqdj5dVFP+B6iI5e9oQP5FSCyPVKSYBx1eTvh++eTE4gaFVZmCOupkexhYR/zXg+RKjIKZ7V77XnYXDpS4F1/rUK4S2brYEndfb8H7U0f24OVQJDEC8yUYM781jR+c3XdkGOm1iO5B/S5oJYUNgHnqO/xkvOaZfD72k0Frj+ih+Om6fWRB7Q4oI/0GW6oRaTrfWyarPqf+KJySKem26V3j4DYMVKLF5rd87lEJXHftPySJILP5sxmzTlRe51VQaxLx40GkIUsD+bF10=
env:
  global:
  - secure: oxWRTAaxKkzYwgQRfql76RjM82vsSo3uADiG5UegEkTLTFYT5Fg9xsHZ/mAcrJQqQ0poXTYHRLTkc8ApT/zMDZhtTsDTzL/Rlb0ykwdzLAoCaFGQr5Y/xWbbB8ahuwno2TilkWbGZyhSws6oCoUl9FaQWz+zp/hnP29qzNt0SbRGVqGfxEyhdymFN09kMrQFpk35EzeSDOXyveW9Tm0LXoNWFDoalNW13WmjVpMPFV2rlXwcV2yyDoiqY5Coa9Mwtuvbu9VrPJxWmPbZXT6IrUlTU2wQkt8QOkYANyK4xQACjrItNQPJNhlpBo1fdGLR5IRp6F3/424gnnQ4exkzqdCqbYfUVIYsLaAohe4Yj6spfk8YB/e4LgeZaP0kd5ZCwrkM7Hn2MXmvOB6L9lHadMqbKk7lshhUJVnaoUKhd4DQL4+VkAXMcKcPbMBDW9dAl+bembQM4Tzgg7hgetrXiVQcrxXdtXH78ksH1KsOWWS+iWuFxt3PovLDNLRyUqiezZvoBtwvzDawPbTtVjbXld+dBeZkLSSYygDT1Ue2ptZVxDn50CLqRn9ep2IacVuOBbzO7Fb9RyM1+VgFcWnyVTD0yCaRXUiZnKn1eLegO5VFJkmIk7flGPA2DPD2ANeG86p0NUmvi7nhLQI9IZfaWtqiPIRxSADsW5sqOwRhEVM=
  - secure: rgQAwYWyxPt0LMt8gvm41LgQop1seDjFZRziLUck14Ras1TEhjYLNkLwdI2tZr4wGFSTjj/9JjIUwHr4QDM05/SRJNHJSyN1hH7R760gVGdR1FKPzt5g7T5wJkw1HfeU7eixA0UKZXk/ADNNQGtKliOINaSs+zr6bzYOlab9GfvXnVhOD5ozwREwuX1pvB3HdAZR/ij3koLA4QDmFa2Hu1N/0SR5iFi5fCjrntWhgj83oZX9E7OPKh2Lm7KOEx9gWwXXPyxS/uudQSaRExu+byuLtVGv/BqYx3bSiitmiDfARofNAUdMrr0Cqi1t6CkTXxdSAgw17htnIcBm9stlLt+29LHbrbHXiPtoMHxYP+x0nKggcKuqt+faG8gD0Ki9e7t2KnsV2zjoTDkAGtFU/sGF9ByO0mSkrJWVnBczI+EFf3pdR22CAoiiXKBzUuYJELrDdk+R4iStsWtKtKfjXq9I+n/rH1IO9ad//J9K38uUuGW0xbvFstg5kkSgS46pktFgXHcJRwWLD8ANQWAhENiUVnE8POFBwnRK5r4v0M0VtSmTJ1f66U62GtsWgRH+hDWqFBUa51QbKDeai4757ukAX4eWdvQ+BXpKgtZW1BT31fEPVK86vPE5tyxfdlSPO8JTGGeFWfuAev6ZGoGW/7ex+buF2PsEGC6xH9dK+9s=
